<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MushaAltSpaceIme.Core/MushaAltSpaceIme.Core.csproj" />
    <Compile Include="../../src/MushaAltSpaceIme/NativeMethods.cs" Link="NativeMethods.cs" />
    <Compile Include="../../src/MushaAltSpaceIme/ShortcutSender.cs" Link="ShortcutSender.cs" />
  </ItemGroup>
</Project>
